// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const attachCartToUser = `-- name: AttachCartToUser :one
UPDATE carts
SET
  user_id = $1::uuid,
  session_id = NULL,
  updated_at = NOW()
WHERE id = $2
RETURNING id, user_id, session_id, status, created_at, updated_at
`

type AttachCartToUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) AttachCartToUser(ctx context.Context, arg AttachCartToUserParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, attachCartToUser, arg.UserID, arg.ID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
  user_id,
  session_id,
  status
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, session_id, status, created_at, updated_at
`

type CreateCartParams struct {
	UserID    uuid.NullUUID
	SessionID sql.NullString
	Status    string
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.UserID, arg.SessionID, arg.Status)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCartBySessionID = `-- name: GetActiveCartBySessionID :one
SELECT id, user_id, session_id, status, created_at, updated_at FROM carts
WHERE session_id = $1::text
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCartBySessionID(ctx context.Context, sessionID string) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartBySessionID, sessionID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCartByUserID = `-- name: GetActiveCartByUserID :one
SELECT id, user_id, session_id, status, created_at, updated_at FROM carts
WHERE user_id = $1::uuid
  AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, user_id, session_id, status, created_at, updated_at FROM carts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCartByID(ctx context.Context, id uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartsByUserID = `-- name: ListCartsByUserID :many
SELECT id, user_id, session_id, status, created_at, updated_at FROM carts
WHERE user_id = $1::uuid
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCartsByUserIDParams struct {
	UserID     uuid.UUID
	OffsetRows int32
	LimitRows  int32
}

func (q *Queries) ListCartsByUserID(ctx context.Context, arg ListCartsByUserIDParams) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCartsByUserID, arg.UserID, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartStatus = `-- name: UpdateCartStatus :one
UPDATE carts
SET
  status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, session_id, status, created_at, updated_at
`

type UpdateCartStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, updateCartStatus, arg.ID, arg.Status)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
