// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (
  cart_id,
  product_id,
  quantity,
  price_cents_snapshot
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, cart_id, product_id, quantity, price_cents_snapshot, created_at
`

type CreateCartItemParams struct {
	CartID             uuid.UUID
	ProductID          uuid.UUID
	Quantity           int32
	PriceCentsSnapshot int32
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, createCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCentsSnapshot,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCentsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemByCartAndProduct = `-- name: GetCartItemByCartAndProduct :one
SELECT id, cart_id, product_id, quantity, price_cents_snapshot, created_at FROM cart_items
WHERE cart_id = $1
  AND product_id = $2
LIMIT 1
`

type GetCartItemByCartAndProductParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItemByCartAndProduct(ctx context.Context, arg GetCartItemByCartAndProductParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByCartAndProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCentsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, product_id, quantity, price_cents_snapshot, created_at FROM cart_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCartItemByID(ctx context.Context, id uuid.UUID) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByID, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCentsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT id, cart_id, product_id, quantity, price_cents_snapshot, created_at FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceCentsSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) RemoveCartItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeCartItem, id)
	return err
}

const removeCartItemByCartAndProduct = `-- name: RemoveCartItemByCartAndProduct :exec
DELETE FROM cart_items
WHERE cart_id = $1
  AND product_id = $2
`

type RemoveCartItemByCartAndProductParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) RemoveCartItemByCartAndProduct(ctx context.Context, arg RemoveCartItemByCartAndProductParams) error {
	_, err := q.db.ExecContext(ctx, removeCartItemByCartAndProduct, arg.CartID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $2
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, price_cents_snapshot, created_at
`

type UpdateCartItemQuantityParams struct {
	ID       uuid.UUID
	Quantity int32
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCentsSnapshot,
		&i.CreatedAt,
	)
	return i, err
}
