// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	SessionID sql.NullString
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CartItem struct {
	ID                 uuid.UUID
	CartID             uuid.UUID
	ProductID          uuid.UUID
	Quantity           int32
	PriceCentsSnapshot int32
	CreatedAt          time.Time
}

type Category struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	ParentID  uuid.NullUUID
	CreatedAt time.Time
}

type Order struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Status               string
	Currency             string
	SubtotalCents        int32
	TotalCents           int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ShippingName         sql.NullString
	ShippingAddressLine1 sql.NullString
	ShippingAddressLine2 sql.NullString
	ShippingCity         sql.NullString
	ShippingPostalCode   sql.NullString
	ShippingCountry      sql.NullString
}

type OrderItem struct {
	ID                  uuid.UUID
	OrderID             uuid.UUID
	ProductID           uuid.UUID
	ProductNameSnapshot string
	PriceCentsSnapshot  int32
	Quantity            int32
	CreatedAt           time.Time
}

type Payment struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	Provider          string
	ProviderPaymentID sql.NullString
	AmountCents       int32
	Currency          string
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CheckoutSessionID sql.NullString
	PaymentIntentID   sql.NullString
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description string
	PriceCents  int32
	Currency    string
	Stock       int32
	IsActive    bool
	Sku         string
	WeightGrams sql.NullInt32
	ImageUrl    sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductCategory struct {
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash sql.NullString
	Phone        sql.NullString
	FullName     string
	Role         string
	IsVerified   bool
	LastLoginAt  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
