// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  user_id,
  status,
  currency,
  subtotal_cents,
  total_cents,
  shipping_name,
  shipping_address_line1,
  shipping_address_line2,
  shipping_city,
  shipping_postal_code,
  shipping_country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, status, currency, subtotal_cents, total_cents, created_at, updated_at, shipping_name, shipping_address_line1, shipping_address_line2, shipping_city, shipping_postal_code, shipping_country
`

type CreateOrderParams struct {
	UserID               uuid.UUID
	Status               string
	Currency             string
	SubtotalCents        int32
	TotalCents           int32
	ShippingName         sql.NullString
	ShippingAddressLine1 sql.NullString
	ShippingAddressLine2 sql.NullString
	ShippingCity         sql.NullString
	ShippingPostalCode   sql.NullString
	ShippingCountry      sql.NullString
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.Currency,
		arg.SubtotalCents,
		arg.TotalCents,
		arg.ShippingName,
		arg.ShippingAddressLine1,
		arg.ShippingAddressLine2,
		arg.ShippingCity,
		arg.ShippingPostalCode,
		arg.ShippingCountry,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingName,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, currency, subtotal_cents, total_cents, created_at, updated_at, shipping_name, shipping_address_line1, shipping_address_line2, shipping_city, shipping_postal_code, shipping_country FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingName,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
	)
	return i, err
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, status, currency, subtotal_cents, total_cents, created_at, updated_at, shipping_name, shipping_address_line1, shipping_address_line2, shipping_city, shipping_postal_code, shipping_country FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Currency,
			&i.SubtotalCents,
			&i.TotalCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShippingName,
			&i.ShippingAddressLine1,
			&i.ShippingAddressLine2,
			&i.ShippingCity,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderShipping = `-- name: UpdateOrderShipping :one
UPDATE orders
SET
  shipping_name = $2,
  shipping_address_line1 = $3,
  shipping_address_line2 = $4,
  shipping_city = $5,
  shipping_postal_code = $6,
  shipping_country = $7,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, currency, subtotal_cents, total_cents, created_at, updated_at, shipping_name, shipping_address_line1, shipping_address_line2, shipping_city, shipping_postal_code, shipping_country
`

type UpdateOrderShippingParams struct {
	ID                   uuid.UUID
	ShippingName         sql.NullString
	ShippingAddressLine1 sql.NullString
	ShippingAddressLine2 sql.NullString
	ShippingCity         sql.NullString
	ShippingPostalCode   sql.NullString
	ShippingCountry      sql.NullString
}

func (q *Queries) UpdateOrderShipping(ctx context.Context, arg UpdateOrderShippingParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderShipping,
		arg.ID,
		arg.ShippingName,
		arg.ShippingAddressLine1,
		arg.ShippingAddressLine2,
		arg.ShippingCity,
		arg.ShippingPostalCode,
		arg.ShippingCountry,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingName,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
  status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, currency, subtotal_cents, total_cents, created_at, updated_at, shipping_name, shipping_address_line1, shipping_address_line2, shipping_city, shipping_postal_code, shipping_country
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.SubtotalCents,
		&i.TotalCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShippingName,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
	)
	return i, err
}
