// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  order_id,
  product_id,
  product_name_snapshot,
  price_cents_snapshot,
  quantity
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, order_id, product_id, product_name_snapshot, price_cents_snapshot, quantity, created_at
`

type CreateOrderItemParams struct {
	OrderID             uuid.UUID
	ProductID           uuid.UUID
	ProductNameSnapshot string
	PriceCentsSnapshot  int32
	Quantity            int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductNameSnapshot,
		arg.PriceCentsSnapshot,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductNameSnapshot,
		&i.PriceCentsSnapshot,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, order_id, product_id, product_name_snapshot, price_cents_snapshot, quantity, created_at FROM order_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductNameSnapshot,
		&i.PriceCentsSnapshot,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, product_name_snapshot, price_cents_snapshot, quantity, created_at FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductNameSnapshot,
			&i.PriceCentsSnapshot,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
