// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  order_id,
  provider,
  provider_payment_id,
  amount_cents,
  currency,
  status,
  checkout_session_id,
  payment_intent_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id
`

type CreatePaymentParams struct {
	OrderID           uuid.UUID
	Provider          string
	ProviderPaymentID sql.NullString
	AmountCents       int32
	Currency          string
	Status            string
	CheckoutSessionID sql.NullString
	PaymentIntentID   sql.NullString
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderPaymentID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.CheckoutSessionID,
		arg.PaymentIntentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const getPaymentByCheckoutSessionID = `-- name: GetPaymentByCheckoutSessionID :one
SELECT id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id FROM payments
WHERE checkout_session_id = $1::text
LIMIT 1
`

func (q *Queries) GetPaymentByCheckoutSessionID(ctx context.Context, checkoutSessionID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByCheckoutSessionID, checkoutSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id FROM payments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const getPaymentByPaymentIntentID = `-- name: GetPaymentByPaymentIntentID :one
SELECT id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id FROM payments
WHERE payment_intent_id = $1::text
LIMIT 1
`

func (q *Queries) GetPaymentByPaymentIntentID(ctx context.Context, paymentIntentID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByPaymentIntentID, paymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const getPaymentByProviderPaymentID = `-- name: GetPaymentByProviderPaymentID :one
SELECT id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id FROM payments
WHERE provider_payment_id = $1::text
LIMIT 1
`

func (q *Queries) GetPaymentByProviderPaymentID(ctx context.Context, providerPaymentID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByProviderPaymentID, providerPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const listPaymentsByOrderID = `-- name: ListPaymentsByOrderID :many
SELECT id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id FROM payments
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByOrderID(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CheckoutSessionID,
			&i.PaymentIntentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderPaymentID = `-- name: SetProviderPaymentID :one
UPDATE payments
SET
  provider_payment_id = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id
`

type SetProviderPaymentIDParams struct {
	ID                uuid.UUID
	ProviderPaymentID sql.NullString
}

func (q *Queries) SetProviderPaymentID(ctx context.Context, arg SetProviderPaymentIDParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, setProviderPaymentID, arg.ID, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET
  status = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, provider, provider_payment_id, amount_cents, currency, status, created_at, updated_at, checkout_session_id, payment_intent_id
`

type UpdatePaymentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CheckoutSessionID,
		&i.PaymentIntentID,
	)
	return i, err
}
