// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addProductCategory = `-- name: AddProductCategory :exec
INSERT INTO product_categories (
  product_id,
  category_id
) VALUES (
  $1, $2
)
ON CONFLICT DO NOTHING
`

type AddProductCategoryParams struct {
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const listCategoriesByProductID = `-- name: ListCategoriesByProductID :many
SELECT c.id, c.name, c.slug, c.parent_id, c.created_at
FROM categories c
INNER JOIN product_categories pc ON pc.category_id = c.id
WHERE pc.product_id = $1
ORDER BY c.name ASC
`

func (q *Queries) ListCategoriesByProductID(ctx context.Context, productID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategoryID = `-- name: ListProductsByCategoryID :many
SELECT p.id, p.name, p.slug, p.description, p.price_cents, p.currency, p.stock, p.is_active, p.sku, p.weight_grams, p.image_url, p.created_at, p.updated_at
FROM products p
INNER JOIN product_categories pc ON pc.product_id = p.id
WHERE pc.category_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListProductsByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.Stock,
			&i.IsActive,
			&i.Sku,
			&i.WeightGrams,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductCategory = `-- name: RemoveProductCategory :exec
DELETE FROM product_categories
WHERE product_id = $1
  AND category_id = $2
`

type RemoveProductCategoryParams struct {
	ProductID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeProductCategory, arg.ProductID, arg.CategoryID)
	return err
}
