// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  slug,
  description,
  price_cents,
  currency,
  stock,
  is_active,
  sku,
  weight_grams,
  image_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at
`

type CreateProductParams struct {
	Name        string
	Slug        string
	Description string
	PriceCents  int32
	Currency    string
	Stock       int32
	IsActive    bool
	Sku         string
	WeightGrams sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.Stock,
		arg.IsActive,
		arg.Sku,
		arg.WeightGrams,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at FROM products
WHERE LOWER(slug) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, lower string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.Stock,
			&i.IsActive,
			&i.Sku,
			&i.WeightGrams,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductActiveStatus = `-- name: SetProductActiveStatus :one
UPDATE products
SET
  is_active = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at
`

type SetProductActiveStatusParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetProductActiveStatus(ctx context.Context, arg SetProductActiveStatusParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, setProductActiveStatus, arg.ID, arg.IsActive)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name = $2,
  slug = $3,
  description = $4,
  price_cents = $5,
  currency = $6,
  stock = $7,
  is_active = $8,
  sku = $9,
  weight_grams = $10,
  image_url = $11,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description string
	PriceCents  int32
	Currency    string
	Stock       int32
	IsActive    bool
	Sku         string
	WeightGrams sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.Stock,
		arg.IsActive,
		arg.Sku,
		arg.WeightGrams,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET
  stock = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, price_cents, currency, stock, is_active, sku, weight_grams, image_url, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID    uuid.UUID
	Stock int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.Stock,
		&i.IsActive,
		&i.Sku,
		&i.WeightGrams,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
