// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  phone,
  full_name,
  role
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash sql.NullString
	Phone        sql.NullString
	FullName     string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at FROM users
WHERE LOWER(email) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at FROM users
WHERE phone = $1::text
LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Phone,
			&i.FullName,
			&i.Role,
			&i.IsVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :one
UPDATE users
SET
  password_hash = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

type SetUserPasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash sql.NullString
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users
SET
  phone = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

type UpdateUserPhoneParams struct {
	ID    uuid.UUID
	Phone sql.NullString
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPhone, arg.ID, arg.Phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
  full_name = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID
	FullName string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET
  role = $2,
  updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET
  is_verified = TRUE,
  updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, phone, full_name, role, is_verified, last_login_at, created_at, updated_at
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.Role,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
